title: Dimas Maulana Arbi
logo: assets/img/IMG20210824143502.jpg
description: A recent Electrical Engineering graduate, I specialize in biomedical research, data science, and backend engineering. I am highly motivated and eager to learn new technologies and methodologies. My strengths include adaptability, critical thinking, and collaboration in team settings. My organizational and work experiences have sharpened my leadership abilities, enhanced my communication skills, and honed my strategic thinking.
show_download: True
theme: jekyll-theme-slate
